### ISSUE TITLE
SSL Handshake issue

### ISSUE THREAD

**Issue by aa403** [jmcarp/betfair.py#16]
I get an SSL handshake issue after uploading my .crt file and running:

``` python
from betfair import Betfair
client = Betfair('my_appid','certs/betfair.pem')
client.login('my_user_name', 'my_pw')
```

where my_appid is taken from `https://developer.betfair.com/visualisers/api-ng-account-operations/getDeveloperAppKeys`

and my_user_name and my_pw are my usual login details.

any ideas?

**Comment by jmcarp** [comment]
The application ID (mine is five digits) isn't the same as the application key (mine is a longer alphanumeric string). Make sure you're using your application key here. If you still run into errors, feel free to post the traceback, but be sure to exclude your username / password / application credentials if you do!

**Comment by aa403** [comment]
yup, that is what I am using (ie the longer alphanumeric)... traceback below, taken from pycharm


/Applications/anaconda/bin/python2.7 /Users/ammarorama/Documents/GIT/betfair.py/scratchpad.py
25-05 22:10:14 requests.packages.urllib3.connectionpool INFO     Starting new HTTPS connection (1): identitysso.betfair.com
Traceback (most recent call last):
  File "/Users/ammarorama/Documents/GIT/betfair.py/scratchpad.py", line 13, in <module>
    client.login('my_user_name', 'my_pw')
  File "/Users/ammarorama/Documents/GIT/betfair.py/betfair/betfair.py", line 90, in login
    'Content-Type': 'application/x-www-form-urlencoded',
  File "/Applications/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 504, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/Applications/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/Applications/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/Applications/anaconda/lib/python2.7/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [Errno 1] _ssl.c:1426: error:140940E5:SSL routines:SSL3_READ_BYTES:ssl handshake failure

Process finished with exit code 1

**Comment by aa403** [comment]
actually ... scratch that, this all seems to be an issue w using anaconda as opposed to the native python implementation ... closing the issue
